### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#122]
The error MAYBE showed up when i added a Manager + Lead Dev and reorganized the developers Auto-Merge. 

OR that it showed up when I was delivering a job, and then tried to deliver another job. 
The error probably came with the last said thing, as I somehow were able to deliver both jobs even if I didnt have enough modules to do so. 

![image](https://cloud.githubusercontent.com/assets/8394703/19452926/3b2b0b9a-94b3-11e6-88b2-f79e5369a278.png)

**Comment by BrutalCSkakan** [comment]
TypeError: Cannot read property 'id' of undefined
    at _.remove.x (file:///C:/Users/Kim/Desktop/Developer%20Tycoon/resources/app.asar/scripts/globalHelpers.js:356:64)
    at Function.D.yn.remove (file:///C:/Users/Kim/Desktop/Developer%20Tycoon/resources/app.asar/libs/lodash.min.js:81:215)
    at job.components.forEach.component (file:///C:/Users/Kim/Desktop/Developer%20Tycoon/resources/app.asar/scripts/globalHelpers.js:356:15)
    at Array.forEach (native)
    at DeliverJob (file:///C:/Users/Kim/Desktop/Developer%20Tycoon/resources/app.asar/scripts/globalHelpers.js:354:24)
    at ctrl.deliverJob (file:///C:/Users/Kim/Desktop/Developer%20Tycoon/resources/app.asar/scripts/jobManager.js:24:21)
    at fn (eval at <anonymous> (file:///C:/Users/Kim/Desktop/Developer%20Tycoon/resources/app.asar/libs/angular.min.js:1:0), <anonymous>:4:266)
    at f (file:///C:/Users/Kim/Desktop/Developer%20Tycoon/resources/app.asar/libs/angular.min.js:252:430)
    at n.$eval (file:///C:/Users/Kim/Desktop/Developer%20Tycoon/resources/app.asar/libs/angular.min.js:133:47)
    at n.$apply (file:///C:/Users/Kim/Desktop/Developer%20Tycoon/resources/app.asar/libs/angular.min.js:133:277)

**Comment by BrutalCSkakan** [comment]
Just reproduced it by being "too fast for the modal", we really need to see if we can fix the modal issue.
Maybe it could be done by disabling everything inside a modal until the animation is done? It feels like it has something to do with the animations atleast.

**Comment by InDieTasten** [comment]
If that is the issue, easiest way would be to add an event catcher. Basically an element appended to the body that stretches over the entire screen, that also concludes an input with autofocus. Then make it transparent and it'll catch all mouse and keyboard events until you remove again. But this is just implementation detail. This may not be relevant. Assumptions have been made.

**Comment by jhovgaard** [comment]
Related to #119
